### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by Tim2110** [dustinfife/flexplot#108]
When I apply the estimates function to my GLMM, I receive the following error: 'Error in round(x$r.squared[1], digits = 3) : 
  non-numeric argument to mathematical function'. If I run the same model pretending a normal distribution (so using lmer instead of glmer), estimates() works perfectly fine. 

I don't know whether flexplot does not work for generalized models or if I made a mistake. I would appreciate any hint. Thanks!

**Comment by dustinfife** [comment]
Can you post the code you're using?

**Comment by Tim2110** [comment]
my models like: modelgam<-glmer(response~A + poly(B,2)) + (1|ID), family=Gamma, data=my.data and 
modelnorm<-lmer(response~A + poly(B,2)) + (1|ID), data=my.data

Then I use : estimates(modelgam) and estimates(modelnorm) where the former is producing the error

**Comment by Tim2110** [comment]
Don't know why most of the code is crossed out, sorry for that. There should be a tilde following the response variable of course.

**Comment by dustinfife** [comment]
This should be fixed with [https://github.com/dustinfife/flexplot/commit/47001ffdf25a18a676873c1c58722b35b1ab00ea](this commit). It's very sparse in the type of estimates it reports, mostly because they're mixed models. Mixed models are tricky to report estimates in many ways. I'll think about how I can make that more informative.
