### ISSUE TITLE
Error in installing flexplot

### ISSUE THREAD

**Issue by Sandra-ctrl** [dustinfife/flexplot#118]
Hi Dustin,
been enjoying your youtube videos and decided to use flexplot for my microbiome data but i had this error while installing flexplot. pls find error below. Thanks for your help with this.

In file.copy(savedcopy, lib, recursive = TRUE) : problem copying C:\Users\Sandra Nnadi\AppData\Local\R\win-library\4.2\00LOCK\processx\libs\x64\processx.dll to C:\Users\Sandra Nnadi\AppData\Local\R\win-library\4.2\processx\libs\x64\processx.dll: Permission denied.

Sandra Nnadi

**Comment by ADunn-serc** [comment]
Hello! I wanted to add to this thread. I tried installing flexplot and received the following message:

Warning in install.packages :
  package ‘flexplot’ is not available for this version of R

**Comment by ADunn-serc** [comment]
Update: I followed the README directions for flexplot installation and it worked.

**Comment by dustinfife** [comment]
@Sandra-ctrl : it looks like this is not a flexplot issue, but a PC (permissions) issue. Maybe try running R as administrator on your computer.

**Comment by Sandra-ctrl** [comment]
@dustinfife Thanks, I tried running R as an administrator and the warning issue came up "permission denied". I agree that it is a PC issue. Thanks

* installing *source* package 'flexplot' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'vctrs' 0.5.1 is being loaded, but >= 0.6.0 is required
Calls: <Anonymous> ... namespaceImport -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'flexplot'
* removing 'C:/Users/Sandra Nnadi/AppData/Local/R/win-library/4.2/flexplot'

**Comment by teach615** [comment]
In case anyone else is having this issue, I realized I needed to install the packages that studio was telling me I only needed to update....so try that if you get this error. It solved the "permission denied" problem for me.

I installed (rather than updating) the packages from the R output below:

These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: Rcpp   (1.0.11 -> 1.0.12) [CRAN]
5: vctrs  (0.6.3  -> 0.6.5 ) [CRAN]
6: glue   (1.6.2  -> 1.7.0 ) [CRAN]
7: rlang  (1.1.1  -> 1.1.3 ) [CRAN]
8: digest (0.6.33 -> 0.6.35) [CRAN]
9: cli    (3.6.1  -> 3.6.2 ) [CRAN]

**Comment by dustinfife** [comment]
Yes, that's the traditional way to fix the problem.
