### ISSUE TITLE
Paneled Histogram, etc.

### ISSUE THREAD

**Issue by BobMuenchen** [dustinfife/flexplot#46]
Nice work on flexplot!  Using R's mtcars data set, I put mpg as outcome and am (automatic vs. manual transmission) as paneled but did not get a paneled histogram as I expected. I tried a similar step to get a paneled bar plot, with no luck.

If those plots had appeared, the panels would have been side-by-side, squishing them up a bit. So an option to make a single paneled variable stack vertically would be nice. An option to use a density or QQ plots instead of a histogram would be helpful for smaller datasets that often don't make very decent histograms.

You mention the disadvantages of box and violin plots. Does that mean you're not thinking of adding them in the future?  Flexplot looks like a really nice alternative to ggplot2, other than those limitations.

I love the ghost lines!  What is the bins argument doing?  How does one control which panel is the one chosen to be the ghost line standard? After writing that I saw the flexplot help file makes it clear, so this is regarding the jamovi interface. When I have jamovi show syntax, it uses "flexplota" which I don't see documented in either the flexplot or jmv packages.

You've got a minor typo in the jamovi blog post where the text under the first AVP screen shot has turned into a table.

Thanks & keep up the good work!

**Comment by dustinfife** [comment]
Hi Bob! Thanks for popping in. I had actually never thought to do paneled histograms. Great idea! It's been added to the development branch of flexplot. You just use the following syntax:

```
data(avengers)
flexplot(speed~1 | agility, data=avengers) 
```

I also modified flexplot so it allows you to panel by rows instead of columns. Here's the syntax:

```
data(avengers)
flexplot(speed~1 | +agility, data=avengers) 
```

Also, now flexplot can do density plots, qqplots, violin plots and boxplots:

```
data(avengers)
flexplot(speed~1 | +agility, data=avengers, plot.type="qq") 
flexplot(speed~1 | +agility, data=avengers, plot.type="density") 
flexplot(speed~superpower, data=avengers, plot.type="boxplot") 
flexplot(speed~superpower, data=avengers, plot.type="violin") 
```

The bins argument controls how many levels are created when categorizing a numeric variable. If bins = 3 (default), all numeric variables that need to be converted are converted into three levels. But, sometimes the right number of bins cannot be made (e.g., if you specified 4 bins for skewed data, the 50th and 75th percentile may have the same value, so it will go down to 3 bins). 

Currently, you can't control the ghost reference from jamovi. I still haven't thought of a good way to do that. 

As for the jamovi syntax, I'm not sure about that one. I wouldn't trust it though. Long story short, to get jamovi to communicate with flexplot, I had to create additional functions (e.g., flexplota) that then prepare the data to communicate with flexplot.

**Comment by BobMuenchen** [comment]
Wow, you’re quick!  Thanks, I’ll pass that along to Jonathon Love.
