### ISSUE TITLE
sorting problem from large to small

### ISSUE THREAD

**Issue by modelistatistik** [dustinfife/flexplot#53]
Hi there,

When creating graphics with flexplot on Jamovi and JASP, I don't want it to automatically sort from large to small. What should I do for this?

The 1th hour in the image I shared below should be next to baseline.

https://prnt.sc/suuwl3

Thanks for helps.

**Comment by dustinfife** [comment]
It's easy in Jamovi: you just have to specify that date is an ordered factor, then specify the order. The idea is the same in JASP, but a little more difficult to implement. I believe you have to rename your factors so that JASP can automatically recognize the ordering (e.g., "A-Baseline", "B-1st Hour"; or "0-Baseline", "1st Hour").

**Comment by modelistatistik** [comment]
The problem still persists.
Let see: 
https://prnt.sc/svy5n3

**Comment by modelistatistik** [comment]
Other version: https://prnt.sc/svy6rq

**Comment by modelistatistik** [comment]
JASP: https://prnt.sc/svy88y

**Comment by dustinfife** [comment]
You have to convert the variables to ordered factors first:

https://www.dropbox.com/s/2pnna4t6bfz6494/Screenshot%202020-06-08%2010.22.42.png?dl=0

**Comment by modelistatistik** [comment]
Its done. Thanks for helps. 

Gokhan.
