### ISSUE TITLE
Problem with visualize function. ... : argument is of length zero

### ISSUE THREAD

**Issue by reecetan7** [dustinfife/flexplot#89]
Hi Dustin,

Thank you for your incredible content and software. I am relatively new to R and am trying to learn it to implement some mixed-effects modeling for my Master's Thesis. I am trying to follow along in your videos on mixed-effects modeling and I'm having some issues with the visualize() function in flexplot. When I implement the following code in R...

install.packages("devtools")
devtools::install_github("dustinfife/flexplot", ref="development")

library(lme4)
library(lmerTest)
library(flexplot)
data(alcuse)
mod = lmer(ALCUSE~1 + (1|ID), data=alcuse)

visualize(mod)

I obtain the following error message:
> visualize(mod)
Error in if (preds[i] != term.re) { : argument is of length zero

I looked through some of the other issues folks were having and I believe you recommended I instal the development version of flexplot, but the problem persisted even after I did so. Do you have any other ideas or solutions? I am running flexplot version 0.13.3, R studio version 2022.02.0, and MacOS Catalina version 10.15.7. 
I am very new to R and github, so please forgive me if my description of the issue isn't clear or if there is other important information I am unintentionally omitting. Just let me know. 

Thanks for all you do!
Tanner

**Comment by dustinfife** [comment]
Hi Tanner,

It looks like the issue is with lmerTest. It seems lmerTest is converting all lmer objects from a "lmerMod" object to a "lmerModLmerTest" object. It's also converting the random effect to a number, while lme4 keeps it as a factor. 

To override this, I'd recommend using the following code:

`mod = lme4::lmer(ALCUSE~1 + (1|ID), data=alcuse)`

By putting `lme4::` before the lmer, it explicitly specifies that you're using lme4's version of the lmer function, not lmerTest's version. Then, if you need whatever functionality lmerTest offers, you'd replace that with `lmerTest::lmer(....)`.  But, when you do this, you won't be able to visualize it. 

Hope that helps!

**Comment by reecetan7** [comment]
Hi Dustin,

Thanks so much for your quick response. I am able to generate plots now. I have one more question if thats okay. I am trying to follow along to your youtube video:[ ](https://youtu.be/Wtk5iZ65XHk?list=PL8F480DgtpW9_IT7xN1XeRF_dglZmK0nM&t=263) 
and when I try to reproduce the graphic that includes the plot for each the fixed and random effects (the red and green plots) and when I plot it, my graphic only includes one model (see attached images). 
Below is the code I used:

rm(list=ls())
require(lme4)
require(flexplot)
data(math)
mod = lme4::lmer(MathAch~1 + (1|School), data=math)
visualize(mod)

Is there anything else I need to do to replicate graphs that include both fixed and random effect plots? 

Thanks,
Tanner
![Screen Shot 2022-03-16 at 8 14 13 PM](https://user-images.githubusercontent.com/101607965/158717818-196e7797-ad8f-4668-972e-db3c4c3dcd5c.png)

![Screen Shot 2022-03-16 at 8 15 32 PM](https://user-images.githubusercontent.com/101607965/158717810-c7d8dc48-ffc3-418f-a9ef-b5a39854278d.png)
